### ISSUE TITLE
gulp + vinyl-transform + browserify

### ISSUE THREAD

**Issue by Dhananjay08** [expressjs/serve-static#130]
```
/node_modules/cloneable-readable/index.js:12
  var objectMode = stream._readableState.objectMode
                                         ^

TypeError: Cannot read property 'objectMode' of undefined
 at new Cloneable (/node_modules/cloneable-readable/index.js:12:42)
    at Cloneable (/node_modules/cloneable-readable/index.js:10:12)
    at File.set (/node_modules/vinyl/index.js:189:13)
    at Transform.write [as _transform] (/node_modules/vinyl-transform/index.js:20:21)
    at Transform._read (/node_modules/vinyl-transform/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/node_modules/vinyl-transform/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/node_modules/vinyl-transform/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/node_modules/vinyl-transform/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/node_modules/vinyl-transform/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at DestroyableTransform.ondata (/node_modules/readable-stream/lib/_stream_readable.js:612:20)
```

**Comment by jonchurch** [comment]
Hello there, I can't tell from this issue how this relates to serve static.

Can you give more information or a reproduction of the issue? Without that I won't be able to figure out what is happening here. Thank you ❤️

**Comment by dougwilson** [comment]
Closing due to no response.
