### ISSUE TITLE
Angular 13 SSR serve is failing with error - TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by hp1493** [expressjs/serve-static#157]
Currently upgraded a legacy app from Angular version v6 to v13 & when trying to deploy the server / serve locally using 'npm run serve:ssr' facing issue in the build packages which is pointing to server static as below 

TypeError: Right-hand side of 'instanceof' is not an object
    at gt (/Users/dist/server.js:3673:146087)
    at pt (/Users/dist/server.js:3673:145962)
    at PA (/Users/dist/server.js:3673:168745)
    at Cn.Vn.insertToken (/Users/dist/server.js:3673:145346)
    at /Users/dist/server.js:3673:148654
    at bt (/Users/dist/server.js:3673:148669)
    at Wn (/Users/dist/server.js:3673:143609)
    at Object.parse (/Users/dist/server.js:3673:142574)
    at Object.t.createDocument (/Users/dist/server.js:3650:472)
    at Object.t.createWindow (/Users/dist/server.js:3650:855)

the corresponding line are 
`
/*!
 * serve-static
 * Copyright(c) 2010 Sencha Inc.
 * Copyright(c) 2011 TJ Holowaychuk
 * Copyright(c) 2014-2016 Douglas Christopher Wilson
 * MIT Licensed
.....
3650 : process:function(A){return n.parse("",!1,A)},document:function(){return n.document()}}},
A.createWindow=function(n,t){var e=A.createDocument(n);

/*!
Parser-Lib
Copyright (c) 2009-2011 Nicholas C. Zakas. All rights reserved.
... line :3673

`
detailed configuration & information : 
https://stackoverflow.com/questions/75853134/angular-12-server-side-rendering-serve-throws-typeerror-right-hand-side-of-i

**Comment by dougwilson** [comment]
Hello, and I'm sorry you are having trouble. Unfortunately, I don't think this module can help, as there is no `instanceof` in our code base. You can view our code base right here on Github: https://github.com/expressjs/serve-static/blob/master/index.js

Without even an `instanceof` in our code base, it would seem to be an impossibility to correct an error in the usage of `instanceof` that doesn't exist. If you can provide further details, perhaps link to where exactly in the code the `instanceof` error is coming from and/or provide full reproduction steps that shows where this `instanceof` is in this module, I can re-open the issue. I'm closing now because you may have opened against the wrong module by accident.

**Comment by hp1493** [comment]
@dougwilson , error seems to be invoked at
at ` Object.t.createWindow` as per the stacktrace  and yes you are correct on ` instance of ` being referenced in line from Parser-Lib module.
So was wondering if these are linked as i couldn't see Parserlib in Server-static dependency tree as well,
Any lead would be really helpful 🙂

**Comment by dougwilson** [comment]
Hi, I have no idea, as even there is no `Object.t.createWindow` in this module, either.

**Comment by hp1493** [comment]
Any idea if express is using above methods top in this module as these are part of minified code as part of server bundles generated

**Comment by dougwilson** [comment]
Well, across the entire code base of express I'm sure `instanceof` is being used many places. You'd need to narrow down exactly which module your `instanceof` error is coming from to be able to figure out what is going on at the least. Nothing in express does `createWindow`, however, as that sounds like a web browser api and express is a server side framework.
